trainingInput:
  runtimeVersion: "2.2"
  pythonVersion: "3.7"
  scaleTier: CUSTOM
  masterType: n1-standard-4
  workerType: n1-standard-4
  workerCount: 2
  scheduling:
    maxWaitTime: 3600s
    maxRunningTime: 7200s
