trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    imageUri: eu.gcr.io/szilard-ml-sandbox/multi-worker:latest
  useChiefInTfConfig: true
  workerType: n1-standard-4
  workerCount: 2
  workerConfig:
    imageUri: eu.gcr.io/szilard-ml-sandbox/multi-worker:latest
  scheduling:
    maxWaitTime: 3600s
    maxRunningTime: 7200s
