trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    imageUri: eu.gcr.io/szilard-ml-sandbox/multi-worker:v2.3.1
  useChiefInTfConfig: true
  workerType: n1-standard-4
  workerCount: 1
  workerConfig:
    imageUri: eu.gcr.io/szilard-ml-sandbox/multi-worker:v2.3.1
  scheduling:
    maxWaitTime: 3600s
    maxRunningTime: 7200s
