version: "3.8"
services:
  chief:
    container_name: chief
    image: ${MULTI_WORKER_CONTAINER}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/creds.json:ro
      - ./data:/data:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/creds.json
      TF_CONFIG: "{
        \"cluster\": {
          \"chief\": [\"chief:2222\"],
          \"worker\": [\"worker:2222\"]
        },
        \"task\": {\"type\": \"chief\", \"index\": 0}
      }"
    command: ${COMMAND}
  worker:
    container_name: worker
    image: ${MULTI_WORKER_CONTAINER}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/creds.json:ro
      - ./data:/data:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/creds.json
      TF_CONFIG: "{
        \"cluster\": {
          \"chief\": [\"chief:2222\"],
          \"worker\": [\"worker:2222\"]
        },
        \"task\": {\"type\": \"worker\", \"index\": 0}
      }"
    command: ${COMMAND}
